---
title: "318Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, cache=TRUE, autodep=TRUE)
source("https://www2.stat.duke.edu/~fl35/code/OW/BinaryTrt_Rdemo.R")

library(tidyverse)
library(mvtnorm)
library(patchwork)
library(survey)
library(PSweight)
library(MatchIt)
library(ggthemes)
library(foreach)
```

```{r}
# simulate a data set with six covariates 
sim_data <- function(n, true_effect, overlap){
  # covariates
  X_con <- rmvnorm(n, rep(0,3), (diag(3) + matrix(1,3,3)) / 2)
  X_dis <- cbind(rbinom(n, 1, 0.5), rbinom(n, 1, 0.5), rbinom(n, 1, 0.5))
  X <- cbind(X_con, X_dis)

  true_coefs_con <- c(0.5, 0.3, 0.1)
  true_coefs_dis <- c(-0.5, -0.3, -0.1)
  
  # true propensity scores
  # take inverse of overlap to improve interpretability
  e <- plogis(c(X_con %*% c(true_coefs_con / overlap) + X_dis %*% c(true_coefs_dis / overlap)))
  # treatment 
  z <- rbinom(n, 1, e)
  
  # mean outcomes
  mu.y <- c(X %*% c(rep(0.5, 3), rep(-0.5, 3))) + z * true_effect
  # true outcomes (mean outcome with noise)
  y <- rnorm(n, mu.y, sd = 1)
  data.frame(e = e, y = y, z = z, X)
}

# simulate a high-dimensional data set with 100 covariates 
sim_highdim_data <- function(n, true_effect, overlap, noise = TRUE){
  
  vars <- 50
  pred_vars <- ifelse(noise, 20, vars)
  # 100 continuous/binary covariates, but only 20 of each are predictive, rest are noise
  X_con <- rmvnorm(n, rep(0,vars), (diag(vars) + matrix(1,vars,vars)) / 2)
  X_dis <- matrix(rbinom(n * vars, 1, 0.5), nrow = n)
  X <- cbind(X_con, X_dis)
  X_pred <- cbind(X_con[,1:pred_vars], X_dis[, 1:pred_vars])

  true_coefs_con <- if(noise){
    seq(0.475, 0, length.out = 20)
  } else {
    seq(0.2, 0, length.out = vars)
  }
  true_coefs_dis <- if(noise){
    seq(-0.475, 0, length.out = 20)
  } else {
    seq(-0.2, 0, length.out = vars)
  }
  
  # true propensity scores
  # take inverse of overlap to improve interpretability
  # divide by 5 to control propensity scores - this yields roughly the same distributions as for the original simulation
  e <- plogis(c(X_con[,1:pred_vars] %*% c(true_coefs_con / overlap) + X_dis[,1:pred_vars] %*% c(true_coefs_dis / overlap)) / 5)
  # treatment 
  z <- rbinom(n, 1, e)
  
  # mean outcomes
  mu.y <- c(X_pred %*% rnorm(2 * pred_vars)) + z * true_effect
  # true outcomes (mean outcome with noise)
  y <- rnorm(n, mu.y, sd = 1)
  data.frame(e = e, y = y, z = z, X)
}

# Example calls
head(sim_data(2000, 2, 0.2))
head(sim_highdim_data(2000, 2, 0.2, FALSE))
```

```{r}
# Plotting propensity scores
overlap_1 <- ggplot(sim_data(2000, 2, 0.1), 
                    aes(x = e, color = as.factor(z))) +
  geom_density(lwd = 1, show.legend = FALSE) +
  theme_light() +
  scale_color_wsj("colors6") +
  ggtitle("Overlap = 0.1") +
  xlab("True Propensity Score")

overlap_2 <- ggplot(sim_data(2000, 2, 0.25), 
                    aes(x = e, color = as.factor(z))) +
  geom_density(lwd = 1, show.legend = FALSE) +
  theme_light() +
  scale_color_wsj("colors6") +
  ggtitle("Overlap = 0.25") +
  xlab("True Propensity Score")

overlap_3 <- ggplot(sim_data(2000, 2, 0.6), 
                    aes(x = e, color = as.factor(z))) +
  geom_density(lwd = 1, show.legend = FALSE) +
  theme_light() +
  scale_color_wsj("colors6") +
  ggtitle("Overlap = 0.6") +
  xlab("True Propensity Score")

overlap_4 <- ggplot(sim_data(2000, 2, 1), 
                    aes(x = e, color = as.factor(z))) +
  geom_density(lwd = 1, show.legend = FALSE) +
  theme_light() +
  scale_color_wsj("colors6") +
  ggtitle("Overlap = 1") +
  xlab("True Propensity Score")

overlap_5 <- ggplot(sim_data(2000, 2, 3), 
                    aes(x = e, color = as.factor(z))) +
  geom_density(lwd = 1, show.legend = FALSE) +
  theme_light() +
  scale_color_wsj("colors6") +
  ggtitle("Overlap = 3") +
  xlab("True Propensity Score")

overlap_6 <- ggplot(sim_data(2000, 2, 10), 
                    aes(x = e, color = as.factor(z))) +
  geom_density(lwd = 1, show.legend = FALSE) +
  theme_light() +
  scale_color_wsj("colors6") +
  ggtitle("Overlap = 10") +
  labs(x = "True Propensity Score", color = "Treatment")

# overlap_4 <- ggplot(sim_highdim_data(2000, 2, 0.25, TRUE), 
#                     aes(x = e, color = as.factor(z))) +
#   geom_density(lwd = 1) +
#   theme_light() +
#   scale_color_wsj("colors6") + 
#   ggtitle("Overlap = 1/4, High-Dimensional Data") +
#   labs(x = "True Propensity Score", color = "Treatment")  

(overlap_1 + overlap_2 + overlap_3) / (overlap_4 + overlap_5 + overlap_6)
```

```{r}
sample.data <- sim_highdim_data(2000, 2, 0.25)
summary(sample.data[, 4:9])
apply(sample.data[, 4:6], 2, sd)

sample.highdim.data <- sim_highdim_data(2000, 2, 0.25)
summary(sample.highdim.data[, 4:9])
```

```{r}
# Generating dataset
sim.data <- sim_highdim_data(1000, 2, 0.25, FALSE)

num_vars <- 6
xnam <- paste("X", 1:num_vars, sep="")
ps.form <- as.formula(paste("z ~ ", paste(xnam, collapse= "+")))
out.form <- as.formula(paste("y ~ ", paste(xnam, collapse= "+")))
```


```{r}
# Implementation of methods 
# IPW and overlap are implemented in PSweight library 
# TODO: implement trimming, asymmetric trimming, matching 

# Returns mean-difference estimator
method_mde <- function(data, y, z){
  data.t <- filter(data, z == 1) 
  data.c <- filter(data, z == 0)
  est <- mean(data.t$y) - mean(data.c$y)
  est_var <- var(data.t$y) / nrow(data.t) + var(data.c$y) / nrow(data.c)
  c(est, sqrt(est_var), est + qnorm(0.025) * sqrt(est_var), est + qnorm(0.975) * sqrt(est_var))
} 

# Returns point estimate, standard error, lower 95% CI bound, upper 95% CI bound for IPW weights
method_ipw <- function(data, ps.form, out.form, y){
  est_tmp <- PSweight(data = data, ps.formula = ps.form, 
                       out.formula = out.form, yname = y, 
                       weight = "IPW")
  sum_tmp <- summary(est_tmp)$estimates
  c(sum_tmp[1], sum_tmp[2], sum_tmp[4], sum_tmp[5])
}

# Returns point estimate, standard error, lower 95% CI bound, upper 95% CI bound for IPW weights with trimming
method_ipwtrimmed <- function(data, ps.form, out.form, y, trim){
  trimmed <- PStrim(data = data, ps.formula = ps.form, zname = 'z', delta = trim)$data
  est_tmp <- PSweight(data = trimmed, ps.formula = ps.form, 
                       out.formula = out.form, yname = y, 
                       weight = "IPW")
  sum_tmp <- summary(est_tmp)$estimates
  c(sum_tmp[1], sum_tmp[2], sum_tmp[4], sum_tmp[5])
}

# Returns point estimate, standard error, lower 95% CI bound, upper 95% CI bound for overlap weights
method_overlap <- function(data, ps.form, out.form, y){
  est_tmp <- PSweight(data = data, ps.formula = ps.form, 
                       out.formula = out.form, yname = y, 
                       weight = "overlap")
  sum_tmp <- summary(est_tmp)$estimates
  c(sum_tmp[1], sum_tmp[2], sum_tmp[4], sum_tmp[5])
}

# Returns point estimate, standard error, lower 95% CI bound, upper 95% CI bound for the "Tudor solution"
method_tudor <- function(data, ps.form, out.form, y, cal){
  # optimal matching doesn't work with calipers 
  matched <- match.data(matchit(ps.form, data = data, method = "nearest", ratio = 1, caliper = cal))
  est_tmp <- PSweight(data = matched, ps.formula = ps.form, 
                       out.formula = out.form, yname = y, 
                       weight = "overlap")
  sum_tmp <- summary(est_tmp)$estimates
  c(sum_tmp[1], sum_tmp[2], sum_tmp[4], sum_tmp[5])
}

# Example calls 
method_mde(sim.data, 'y', 'z')
method_ipw(sim.data, ps.form, out.form, 'y')
method_ipwtrimmed(sim.data, ps.form, out.form, 'y', 0.1)
method_overlap(sim.data, ps.form, out.form, 'y')
method_tudor(sim.data, ps.form, out.form, 'y', 0.2)
```

```{r, warning=FALSE}
# Simulation
# This is [very] slow
ests_list_0.25 = list()
for (i in 1:1000){
  if (i %% 100 == 0){print(i)}
  tmp_sim <- sim_data(2000, 2, 0.25)
  ests_list_0.25[[i]] <- matrix(rep(0, len = 20), nrow = 5)
  for(j in 1:5){
	  ests_list_0.25[[i]][j,] <- switch(j, method_mde(tmp_sim, 'y', 'z'),
	                                  method_ipw(tmp_sim, ps.form, out.form, 'y'),
	                                  method_ipwtrimmed(tmp_sim, ps.form, out.form, 'y', 0.1),
	                                  method_overlap(tmp_sim, ps.form, out.form, 'y'), 
	                                  method_tudor(tmp_sim, ps.form, out.form, 'y', 0.2))
  }
}
```


```{r}
ce <- as.matrix(plyr::ldply(hd_noise_ests_list, function(x){x[,1]}))
test_df <- data.frame(mde = ce[,1], ipw = ce[,2], ipw_trimmed = ce[,3], ow = ce[,4], tudor = ce[,5])
summary(test_df)
test_df <- reshape2::melt(test_df)
small_test_df <- data.frame(ipw_trimmed = ce[,3], ow = ce[,4], tudor = ce[,5]) %>% reshape2::melt() 

ggplot(test_df, aes(x = value, color = variable)) +
  geom_density(lwd = 1.2) +
  theme_light() + 
  scale_color_wsj("colors6") +
  ggtitle("Densities of Causal Estimands for Simulated Data, Overlap = 0.25")
ggplot(small_test_df, aes(x = value, color = variable)) +
  geom_density(lwd = 1.2) +
  theme_light() + 
  scale_color_wsj("colors6") +
  ggtitle("Densities for High-Dimensional Data without Noise")
  
```

```{r}
se <- as.matrix(plyr::ldply(ests_list_0.25, function(x){x[,2]}))
ci.lower <- as.matrix(plyr::ldply(ests_list_0.25, function(x){x[,3]}))
ci.upper <- as.matrix(plyr::ldply(ests_list_0.25, function(x){x[,4]}))

coverage_mde <- mean(ci.lower[,1] <= 2 & ci.upper[,1] >= 2)
coverage_ipw <- mean(ci.lower[,2] <= 2 & ci.upper[,2] >= 2)
coverage_ipwtrimmed <- mean(ci.lower[,3] <= 2 & ci.upper[,3] >= 2)
coverage_ow <- mean(ci.lower[,4] <= 2 & ci.upper[,4] >= 2)
coverage_tudor <- mean(ci.lower[,5] <= 2 & ci.upper[,5] >= 2)
```

```{r}
# ests_list_high was generated with overlap = 0.5
emp_high <- sd(ests_list_high[[4]][,1])
cons_high <- mean(ests_list_high[[4]][,2])

# ests_list_low was generated with overlap = 0.2
emp_low <- sd(ests_list_low[[4]][,1])
cons_low <- mean(ests_list_low[[4]][,2])

# hd_ests_list was generated with overlap = 0.25
emp_hd <- sd(ce[,4])
cons_hd <- mean(se[,4])
```

